
<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Ordens de Serviço</h2>
                </div>
                <div class="col-sm-6">
                    <a href="ordemServico/report" class="btn btn-primary"><i class="fas fa-file-alt"></i><span>Relatório</span></a>
                    <a href="#modal-create" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Adicionar</span></a>
                    <a class="btn btn-danger" id="btn-delete-ordens-servico"><i class="material-icons">&#xE15C;</i> <span>Remover</span></a>
                </div>
            </div>
        </div>
        <div class="row filter">
            <div class="col-sm-6">&nbsp</div>
            <div class="col-sm-3">
                <span class="filter">Filtrar Ordens de Serviços:</span>
            </div>
            <div class="col-sm-3">
                <select class="form-control form-control-sm" id="filtroOrdens">
                    <option value="1">Todos</option>
                    <option value="2">Pendentes (Mais antigos)</option>
                    <option value="3">Pendentes (Mais recentes)</option>
                    <option value="4">Finalizado (Mais antigos)</option>
                    <option value="5">Finalizado (Mais recentes)</option>
                </select>
            </div>
        </div>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>
                    <span class="custom-checkbox">
                        <input type="checkbox" id="selectAll">
                        <label for="selectAll"></label>
                    </span>
                </th>
                <th>Cliente</th>
                <th>Nota Fiscal</th>
                <th>Data Emissão</th>
                <th>Garantia</th>
                <th>Status</th>
                <th>Ações</th>
                <th>Finalizar/Imprimir</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->ordensServico as $ordemServico) : ?>
                <tr data-id="<?php echo $ordemServico['id_ordem_servico']; ?>">
                    <td>
                        <span class="custom-checkbox">
                            <input type="checkbox" name="options[]" value="<?php echo $ordemServico['id_ordem_servico']; ?>">
                            <label for="checkbox1"></label>
                        </span>
                    </td>
                    <td><?php echo $ordemServico['nome_cliente'] ?></td>
                    <td><?php echo $ordemServico['nota_fiscal'] ?></td>
                    <td><?php echo date_format(date_create($ordemServico['data_emissao'] ),"d/m/Y"); ?></td>
                    <td><?php echo $ordemServico['status_garantia'] ?></td>
                    <td><i class="<?php echo $ordemServico['status'] === 'Pendente'? 'fas fa-circle color-red': 'fas fa-circle color-green' ?>"></i> <?php echo $ordemServico['status'] ?></td>
                    <td class="btn-group-actions">
                        <a class="<?php echo $ordemServico['status'] === 'Pendente'? 'edit update-ordem-servico': 'edit update-ordem-servico icon-disable' ?>" >
                            <i class="material-icons" data-toggle="tooltip" title="Editar Ordem de Serviço" >&#xE254;</i>
                        </a>
                        <a class="delete delete-ordem-servico">
                            <i class="material-icons" data-toggle="tooltip" title="Deletar Ordem de Serviço">&#xE872;</i>
                        </a>
                    </td>
                    <td class="btn-group-actions">
                        <?php if($ordemServico['status'] === 'Pendente') : ?>
                            <a class="finalizar finalizar-ordem-servico">
                                <i class="far fa-calendar-check" data-toggle="tooltip" title="Finalizar Ordem de Serviço"></i>
                            </a>
                        <?php else : ?>
                            <a href="<?php echo '/ordemServico/imprimir/' . $ordemServico['id_ordem_servico'];?>" class="imprimir imprimir-ordem-servico">
                                <i class="fas fa-print" data-toggle="tooltip" title="Imprimir Ordem de Serviço"></i>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php include 'create.phtml';?>
<?php include 'update.phtml';?>
<?php include 'delete.phtml';?>
<?php include 'finish.phtml';?>

<script type="text/javascript" src="/application/views/ordem-servico/ordemServico.js"></script>



