<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Teste de Programação Telecontrol</title>
    <link rel="shortcut icon" href="/public/images/favicon-telecontrol.png">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link href="/public/css/bootstrap.min.css" rel="stylesheet">
    <link href="/public/css/simple-sidebar.css" rel="stylesheet">
    <link href="/public/css/style.css" rel="stylesheet">
    <link href="/public/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="/public/js/jquery.min.js"></script>
    <script src="/public/js/bootstrap.min.js"></script>
    <script src="/public/js/custom.js"></script>
    <script src="/public/js/jquery.mask.js"></script>
    <script src="/public/js/jquery.maskMoney.js"></script>
    <script src="/public/js/jquery.dataTables.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item active">

                <a class="nav-link login" href="/autenticacao/logout"><i class="fas fa-sign-out-alt"></i>Logout <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>
<div class="d-flex" id="wrapper">
    <div class="bg-light border-right" id="sidebar-wrapper">
        <div class="sidebar-heading">Menu </div>
        <div class="list-group list-group-flush">
            <a href="/ordemServico" class="list-group-item list-group-item-action bg-light">Ordens de Serviço</a>
            <a href="/fornecedor" class="list-group-item list-group-item-action bg-light">Fornecedores</a>
            <a href="/cliente" class="list-group-item list-group-item-action bg-light">Clientes</a>
            <a href="/produto" class="list-group-item list-group-item-action bg-light">Produtos</a>
            <a href="/item" class="list-group-item list-group-item-action bg-light">Itens</a>
            <a href="/servico" class="list-group-item list-group-item-action bg-light">Serviços</a>
        </div>
    </div>
    <div id="page-content-wrapper">
        <div class="container-fluid layout">
            <!-- inclui a view do controller e de sua respectiva ação !-->
            <?php include_once $this->view; ?>
        </div>
    </div>
</div>
</body>
</html>