<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="/public/images/favicon-telecontrol.png">
    <link href="/public/css/bootstrap.min.css" rel="stylesheet">
    <link href="/public/css/login.css" rel="stylesheet">
    <script src="/public/js/jquery.min.js"></script>
    <script src="/public/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="simple-login-container">
        <?php include_once $this->view; ?>
    </div>
</body>
