<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Fornecedores</h2>
                </div>
                <div class="col-sm-6">
                    <a href="#modal-create" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Adicionar</span></a>
                    <a class="btn btn-danger"  id="btn-delete-fornecedores"><i class="material-icons">&#xE15C;</i> <span>Remover</span></a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>
                    <span class="custom-checkbox">
                        <input type="checkbox" id="selectAll">
                        <label for="selectAll"></label>
                    </span>
                </th>
                <th>Nome Fantasia</th>
                <th>Razão Social</th>
                <th>CNPJ</th>
                <th>Endereço</th>
                <th>Bairro</th>
                <th>Número</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->fornecedores as $fornecedor) : ?>

                <tr data-id="<?php echo $fornecedor['id_fornecedor']; ?>">
                    <td>
                        <span class="custom-checkbox">
                            <input type="checkbox" name="options[]" value="<?php echo $fornecedor['id_fornecedor']; ?>">
                            <label for="checkbox1"></label>
                        </span>
                    </td>
                    <td><?php echo $fornecedor['nome_fantasia'] ?></td>
                    <td><?php echo $fornecedor['razao_social'] ?></td>
                    <td><?php echo $fornecedor['cnpj'] ?></td>
                    <td><?php echo $fornecedor['endereco_rua'] ?></td>
                    <td><?php echo $fornecedor['endereco_bairro'] ?></td>
                    <td><?php echo $fornecedor['endereco_numero'] ?></td>
                    <td>
                        <a class="edit update-fornecedor">
                            <i class="material-icons" data-toggle="tooltip" title="Editar Registro">&#xE254;</i>
                        </a>
                        <a class="delete delete-fornecedor">
                            <i class="material-icons" data-toggle="tooltip" title="Deletar Registro">&#xE872;</i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php include 'create.phtml';?>
<?php include 'update.phtml';?>
<?php include 'delete.phtml';?>

<script type="text/javascript" src="/application/views/fornecedor/fornecedor.js"></script>



