<!-- Add Modal HTML -->
<div id="modal-update" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="fornecedor/update" method="POST">
                <div class="modal-header">
                    <h4 class="modal-title">Adicionar Fornecedor</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <input type="hidden" class="form-control" name="idFornecedor">
                        <div class="col-md-8 col-xs-8 no-padding">
                            <div class="form-group">
                                <label for="nomeFantasia">Nome Fantasia</label>
                                <input type="text" class="form-control" name="nomeFantasia" required>
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-4 no-padding">
                            <div class="form-group">
                                <label for="cnpj">CNPJ</label>
                                <input type="number" class="form-control" name="cnpj" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-xs-12 no-padding">
                            <div class="form-group">
                                <label for="razaoSocial">Razão Social</label>
                                <input type="text" class="form-control" name="razaoSocial" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-xs-6 no-padding">
                            <div class="form-group">
                                <label for="enderecoRua">Endereço</label>
                                <input type="text" class="form-control" name="enderecoRua" required>
                            </div>
                        </div>
                        <div class="col-md-2 col-xs-2 no-padding">
                            <div class="form-group">
                                <label for="enderecoNumero">Número</label>
                                <input type="number" class="form-control" name="enderecoNumero" required>
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-4 no-padding">
                            <div class="form-group">
                                <label for="enderecoBairro">Bairro</label>
                                <input type="text" class="form-control" name="enderecoBairro" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Editar</button>
                </div>
            </form>
        </div>
    </div>
</div>