<!-- Add Modal HTML -->
<div id="modal-create" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="item/create" method="POST">
                <div class="modal-header">
                    <h4 class="modal-title">Adicionar Item</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-8 col-xs-8 no-padding">
                            <div class="form-group">
                                <label for="descricaoItem">Descrição</label>
                                <input type="text" class="form-control" name="descricaoItem">
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-4 no-padding">
                            <div class="form-group">
                                <label for="unidadeItem">Unidade de Medida</label>
                                <select class="form-control" name="unidadeItem" required>
                                    <option></option>
                                    <option value="Unidades">Unidades</option>
                                    <option value="Metros">Metros</option>
                                    <option value="Centímetros">Centímetros</option>
                                    <option value="Quilogrmas">Quilogramas</option>
                                    <option value="Gramas">Gramas</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
</div>
