
<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Itens</h2>
                </div>
                <div class="col-sm-6">
                    <a href="#modal-create" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Adicionar</span></a>
                    <a class="btn btn-danger"  id="btn-delete-itens"><i class="material-icons">&#xE15C;</i> <span>Remover</span></a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>
                    <span class="custom-checkbox">
                        <input type="checkbox" id="selectAll">
                        <label for="selectAll"></label>
                    </span>
                </th>
                <th>Descrição</th>
                <th>Unidade de Medida</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->itens as $item) : ?>

                <tr data-id="<?php echo $item['id_item']; ?>">
                    <td>
                        <span class="custom-checkbox">
                            <input type="checkbox" name="options[]" value="<?php echo $item['id_item']; ?>">
                            <label for="checkbox1"></label>
                        </span>
                    </td>
                    <td><?php echo $item['descricao_item'] ?></td>
                    <td><?php echo $item['unidade_item'] ?></td>
                    <td>
                        <a class="edit update-item">
                            <i class="material-icons" data-toggle="tooltip" title="Editar Registro">&#xE254;</i>
                        </a>
                        <a class="delete delete-item">
                            <i class="material-icons" data-toggle="tooltip" title="Deletar Registro">&#xE872;</i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php include 'create.phtml';?>
<?php include 'update.phtml';?>
<?php include 'delete.phtml';?>

<script type="text/javascript" src="/application/views/item/item.js"></script>



