
<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Produtos</h2>
                </div>
                <div class="col-sm-6">
                    <a href="#modal-importar" class="btn btn-primary" data-toggle="modal"><i class="fas fa-upload"></i><span>Importar</span></a>
                    <a href="#modal-create" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Adicionar</span></a>
                    <a class="btn btn-danger"  id="btn-delete-produtos"><i class="material-icons">&#xE15C;</i> <span>Remover</span></a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>
                    <span class="custom-checkbox">
                        <input type="checkbox" id="selectAll">
                        <label for="selectAll"></label>
                    </span>
                </th>
                <th>Referência</th>
                <th>Descrição</th>
                <th>Tensão</th>
                <th>Garantia</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->produtos as $produto) : ?>

                <tr data-id="<?php echo $produto['id_produto']; ?>">
                    <td>
                        <span class="custom-checkbox">
                            <input type="checkbox" name="options[]" value="<?php echo $produto['id_produto']; ?>">
                            <label for="checkbox1"></label>
                        </span>
                    </td>
                    <td><?php echo $produto['referencia_produto'] ?></td>
                    <td><?php echo $produto['descricao_produto'] ?></td>
                    <td><?php echo $produto['tensao_produto'] . 'V'?></td>
                    <td><?php echo $produto['garantia_produto'] . ' Meses' ?></td>
                    <td>
                        <a class="edit update-produto">
                            <i class="material-icons" data-toggle="tooltip" title="Editar Registro">&#xE254;</i>
                        </a>
                        <a class="delete delete-produto">
                            <i class="material-icons" data-toggle="tooltip" title="Deletar Registro">&#xE872;</i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php include 'create.phtml';?>
<?php include 'update.phtml';?>
<?php include 'delete.phtml';?>
<?php include 'importar.phtml';?>

<script type="text/javascript" src="/application/views/produto/produto.js"></script>



