<!-- Edit Modal HTML -->
<div id="modal-update" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="produto/update" method="POST">
                <div class="modal-header">
                    <h4 class="modal-title">Editar Produto</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <input type="hidden" class="form-control" name="idProduto" required>
                    <div class="row">
                        <div class="col-md-12 col-xs-12 no-padding">
                            <div class="form-group">
                                <label for="descricaoProduto">Descrição</label>
                                <input type="text" class="form-control" name="descricaoProduto" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-xs-4 no-padding">
                            <div class="form-group">
                                <label for="referenciaProduto">Referência</label>
                                <input type="text" class="form-control" name="referenciaProduto" required>
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-4 no-padding">
                            <div class="form-group">
                                <label for="tensaoProduto">Tensão</label>
                                <select class="form-control" name="tensaoProduto" required>
                                    <option></option>
                                    <option value="110">110V</option>
                                    <option value="220">220V</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-4 no-padding">
                            <div class="form-group">
                                <label for="garantiaProduto">Garantia em Meses</label>
                                <input type="number" class="form-control" name="garantiaProduto">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Editar</button>
                </div>
            </form>
        </div>
    </div>
</div>
