<h2>Login</h2>

<form action="/autenticacao/login" method="POST">
    <div class="row">
        <div class="col-md-12 form-group">
            <input type="text" class="form-control" name="email_usuario" placeholder="Usuário">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 form-group">
            <input type="password" placeholder="Informe sua senha" name="senha_usuario" class="form-control">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 form-group">
            <input type="submit" class="btn btn-block btn-login" value="Logar">
        </div>
    </div>
</form>
